#!/usr/bin/env python3
"""
Smart ATS Setup Script
Automates the setup process for the Smart ATS application
"""

import os
import sys
import subprocess
import secrets

def print_header(text):
    """Print formatted header"""
    print("\n" + "="*60)
    print(f"  {text}")
    print("="*60 + "\n")

def print_step(step, description):
    """Print step information"""
    print(f"[{step}] {description}")

def check_python_version():
    """Check if Python version is compatible"""
    print_step("✓", "Checking Python version...")
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 8):
        print("❌ Error: Python 3.8 or higher is required")
        print(f"   Current version: {version.major}.{version.minor}.{version.micro}")
        sys.exit(1)
    print(f"   ✓ Python {version.major}.{version.minor}.{version.micro} detected")

def create_directories():
    """Create necessary directories"""
    print_step("📁", "Creating directories...")
    directories = ['uploads', 'static', 'templates']
    for directory in directories:
        if not os.path.exists(directory):
            os.makedirs(directory)
            print(f"   ✓ Created {directory}/")
        else:
            print(f"   ✓ {directory}/ already exists")

def create_env_file():
    """Create .env file with generated secret key"""
    print_step("🔑", "Setting up environment variables...")
    
    if os.path.exists('.env'):
        overwrite = input("   .env file already exists. Overwrite? (y/N): ").lower()
        if overwrite != 'y':
            print("   ⏭  Skipping .env creation")
            return
    
    # Generate secure secret key
    secret_key = secrets.token_hex(32)
    
    env_content = f"""# Smart ATS Environment Configuration
# Generated by setup script

# Flask secret key (keep this secret!)
SECRET_KEY={secret_key}

# Google Gemini API Key
# Get yours at: https://makersuite.google.com/app/apikey
GEMINI_API_KEY=your-gemini-api-key-here

# Application Settings
FLASK_ENV=development
FLASK_DEBUG=True
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("   ✓ Created .env file with generated secret key")
    print("   ⚠  Remember to add your GEMINI_API_KEY to .env file!")

def install_dependencies():
    """Install Python dependencies"""
    print_step("📦", "Installing dependencies...")
    
    if not os.path.exists('requirements.txt'):
        print("   ❌ requirements.txt not found!")
        return False
    
    try:
        subprocess.check_call([
            sys.executable, "-m", "pip", "install", "-r", "requirements.txt"
        ])
        print("   ✓ All dependencies installed successfully")
        return True
    except subprocess.CalledProcessError:
        print("   ❌ Failed to install dependencies")
        return False

def create_gitignore():
    """Create .gitignore file"""
    print_step("🚫", "Creating .gitignore...")
    
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual Environment
venv/
ENV/
env/

# Flask
instance/
.webassets-cache

# Environment variables
.env
.env.local

# Uploads folder
uploads/
*.pdf

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Logs
*.log
"""
    
    with open('.gitignore', 'w') as f:
        f.write(gitignore_content)
    
    print("   ✓ Created .gitignore file")

def verify_files():
    """Verify all required files exist"""
    print_step("✅", "Verifying project structure...")
    
    required_files = {
        'app.py': 'Main application file',
        'requirements.txt': 'Dependencies list',
        '.env': 'Environment variables',
    }
    
    missing = []
    for file, description in required_files.items():
        if os.path.exists(file):
            print(f"   ✓ {file} - {description}")
        else:
            print(f"   ❌ {file} - {description} (MISSING)")
            missing.append(file)
    
    return len(missing) == 0

def print_next_steps():
    """Print instructions for next steps"""
    print_header("✨ Setup Complete!")
    
    print("📝 Next Steps:\n")
    print("1. Get your Google Gemini API key:")
    print("   → Visit: https://makersuite.google.com/app/apikey")
    print("   → Create an API key")
    print("   → Copy the key\n")
    
    print("2. Update your .env file:")
    print("   → Open .env in a text editor")
    print("   → Replace 'your-gemini-api-key-here' with your actual API key\n")
    
    print("3. Run the application:")
    print("   → python app.py")
    print("   → Open browser to http://localhost:5000\n")
    
    print("4. (Optional) Create virtual environment:")
    print("   → python -m venv venv")
    print("   → Windows: venv\\Scripts\\activate")
    print("   → macOS/Linux: source venv/bin/activate")
    print("   → pip install -r requirements.txt\n")
    
    print("📚 For more information, check README.md\n")
    print("🎉 Happy analyzing! - ATS Checker\n")

def main():
    """Main setup function"""
    print_header("🚀 ATS Checker - Setup Wizard")
    
    print("This script will set up the Smart ATS application on your system.\n")
    
    try:
        # Step 1: Check Python version
        check_python_version()
        
        # Step 2: Create directories
        create_directories()
        
        # Step 3: Create .env file
        create_env_file()
        
        # Step 4: Create .gitignore
        create_gitignore()
        
        # Step 5: Install dependencies
        install = input("\n❓ Install Python dependencies now? (Y/n): ").lower()
        if install != 'n':
            install_dependencies()
        else:
            print("   ⏭  Skipped dependency installation")
            print("   💡 Run 'pip install -r requirements.txt' manually later")
        
        # Step 6: Verify setup
        if verify_files():
            print("\n✅ All required files present!")
        else:
            print("\n⚠️  Some files are missing. Please check the output above.")
        
        # Step 7: Print next steps
        print_next_steps()
        
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup failed with error: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    main()